name: github-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main
      
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxe Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib install flixel 6.1.0
          haxelib install flixel-addons 3.3.2
          haxelib git haxeui-core https://github.com/haxeui/haxeui-core 0212d8fdfcafeb5f0d5a41e1ddba8ff21d0e183b
          haxelib git haxeui-flixel https://github.com/haxeui/haxeui-flixel 63a906a6148958dbfde8c7b48d90b0693767fd95
          haxelib install hscript
          haxelib git polymod https://github.com/larsiusprime/polymod scripting-updates
          haxelib git thx.core https://github.com/fponticelli/thx.core.git
          haxelib install thx.semver
          haxelib git jsonpath https://github.com/EliteMasterEric/jsonpath.git
          haxelib install jsonpatch
          haxelib install firetongue
          haxelib install hxgamemode
          haxelib install hxdiscord_rpc
          haxelib install hxcpp-debug-server
          haxelib install extension-androidtools
          haxelib install dox
          haxelib install format
          haxelib list
          mkdir pages
      
      - name: Create Documentation Site
        run: |
            chmod +x docs/docs.sh
            docs/docs.sh
      
      - name: github-actions deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pages